### PR TITLE
Fix equality comparisons in Provisioning model objects

### PR DESCRIPTION
**Pull request by orty**
- Fix equality comparisons in Provisioning model objects
- Added a method extension to compare SecureStrings
- Fixed access to nullable `SharingSettings` property

### CODE REVIEW

**Comment by orty** [comment]
I would like to propose this set of updates, regarding the issue #408 :)

**Comment by orty** [comment]
Hi @PaoloPia,

Did you have a chance to review this pull request so far ? We had to put a lot of workarounds in our code to make it work with the current version of the framework. I am well opened to discuss about any change you might have a doubt on.

**Comment by PaoloPia** [comment]
Hi @orty,
Thanks for your contribution and sorry for the delay. I've been heavily busy with other community projects. I've just evaluated your PR and it is definitely a good one. I'm going to merge it. Thanks!

**Comment by orty** [comment]
Hi @PaoloPia,
No worries, thanks for your validation! Looking forward to seeing this in master ^^

**Pull request merged**
